### ISSUE TITLE
Input 'save-always' has been deprecated

### ISSUE THREAD

**Issue by extrawurst** [Leafwing-Studios/cargo-cache#37]
Not sure when this started but using the github action emits deprecation warnings in current `v2`:

```
Warning: Input 'save-always' has been deprecated with message: save-always does not work as intended and will be removed in a future release.
A separate `actions/cache/restore` step should be used instead.
See https://github.com/actions/cache/tree/main/save#always-save-cache for more details.
```

we make fairly common use of this action via:

```
      - uses: leafwing-studios/cargo-cache@v2
        with:
          sweep-cache: true`
```

**Comment by BD103** [comment]
Looks like this is because make `save-always` default to true:

https://github.com/Leafwing-Studios/cargo-cache/blob/2d82abeae5844ce33b88f8e76d7d6f49c020d04a/action.yml#L32-L37

https://github.com/Leafwing-Studios/cargo-cache/blob/2d82abeae5844ce33b88f8e76d7d6f49c020d04a/action.yml#L160

We should [switch to use `always()` instead](https://github.com/actions/cache/tree/2cdf405574d6ef1f33a1d12acccd3ae82f47b3f2/save#always-save-cache).
